[package]
name = "dlm"
version = "0.3.5"
authors = ["Arnaud Gourlay <arnaud.gourlay@gmail.com>"]
description = "Minimal download manager"
edition = "2021"

[dependencies]
futures = "0.3.28"
futures-util = "0.3.28"
reqwest = { version = "0.11.21", default-features = false, features = ["gzip", "rustls-tls"] }
tokio-stream = { version = "0.1.14", features = ["io-util"] }
tokio = { version = "1.32.0", features = ["rt-multi-thread", "fs", "macros"] }
tokio-retry = "0.3.0"
async-channel = "1.9.0"
chrono = "0.4.31"
clap = { version = "4.4.6", features = ["cargo"] }
indicatif = "0.17.7"
thiserror = "1.0.49"
rand = "0.8.5"
