[package]
name = "dlm"
version = "0.3.5"
authors = ["Arnaud Gourlay <arnaud.gourlay@gmail.com>"]
description = "Minimal download manager"
edition = "2021"

[dependencies]
futures = "0.3.28"
futures-util = "0.3.28"
reqwest = { version = "0.11.18", default-features = false, features = ["gzip", "rustls-tls"] }
tokio-stream = { version = "0.1.14", features = ["io-util"] }
tokio = { version = "1.28.2", features = ["rt-multi-thread", "fs", "macros"] }
tokio-retry = "0.3.0"
async-channel = "1.8.0"
chrono = "0.4.25"
clap = { version = "4.3.0", features = ["cargo"] }
indicatif = "0.17.3"
thiserror = "1.0.40"
rand = "0.8.5"
