[package]
name = "dlm"
version = "0.2.5"
authors = ["Arnaud Gourlay <arnaud.gourlay@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.3.21"
futures-util = "0.3.21"
hyper = "0.14.17"
reqwest = "0.11.10"
tokio-stream = { version = "0.1.8", features = ["io-util"] }
tokio = { version = "1.17", features = ["rt-multi-thread", "fs", "macros"] }
tokio-retry = "0.3"
async-channel = "1.6.1"
chrono = "0.4.19"
clap = "3.1.6"
indicatif = "0.17.0-rc.9"
thiserror = "1.0.30"
rand = "0.8.5"
