[package]
name = "dlm"
version = "0.1.0"
authors = ["Arnaud Gourlay <arnaud.gourlay@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.3.1"
reqwest = "0.10.0-alpha.2"
tokio = "0.2.0-alpha.6"
clap = "2.33.0"
indicatif = "0.13.0"