[package]
name = "dlm"
version = "0.2.6"
authors = ["Arnaud Gourlay <arnaud.gourlay@gmail.com>"]
edition = "2021"

[dependencies]
futures = "0.3.21"
futures-util = "0.3.21"
reqwest = "0.11.10"
tokio-stream = { version = "0.1.8", features = ["io-util"] }
tokio = { version = "1.18", features = ["rt-multi-thread", "fs", "macros"] }
tokio-retry = "0.3"
async-channel = "1.6.1"
chrono = "0.4.19"
clap = "3.1.17"
indicatif = "0.17.0-rc.10"
thiserror = "1.0.31"
rand = "0.8.5"
