[package]
name = "dlm"
version = "0.1.0"
authors = ["Arnaud Gourlay <arnaud.gourlay@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.3.4"
futures-util = "0.3.4"
hyper = "0.13.4"
reqwest = "0.10.4"
tokio = { version = "0.2.18", features = ["full"] }
futures-retry = "0.5.0"
chrono = "0.4.11"
clap = "2.33.0"
indicatif = "0.14.0"
