[package]
name = "dlm"
version = "0.3.7"
authors = ["Arnaud Gourlay <arnaud.gourlay@gmail.com>"]
description = "Minimal download manager"
repository = "https://github.com/agourlay/dlm"
license = "Apache-2.0"
readme = "README.md"
categories = ["command-line-utilities"]
keywords = ["cli", "http", "download", "download-manager"]
edition = "2021"

[dependencies]
futures = "0.3.30"
futures-util = "0.3.30"
reqwest = { version = "0.11.26", default-features = false, features = ["gzip", "rustls-tls"] }
tokio-stream = { version = "0.1.14", features = ["io-util"] }
tokio = { version = "1.36.0", features = ["rt-multi-thread", "fs", "macros"] }
tokio-retry = "0.3.0"
async-channel = "2.2.0"
chrono = "0.4.35"
clap = { version = "4.5.2", features = ["cargo"] }
indicatif = "0.17.8"
thiserror = "1.0.58"
rand = "0.8.5"
