[package]
name = "dlm"
version = "0.2.0"
authors = ["Arnaud Gourlay <arnaud.gourlay@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.3.19"
futures-util = "0.3.19"
hyper = "0.14.16"
reqwest = "0.11.9"
tokio-stream = { version = "0.1.8", features = ["io-util"] }
tokio = { version = "1.15", features = ["rt-multi-thread", "fs", "macros"] }
tokio-retry = "0.3"
async-channel = "1.6.1"
chrono = "0.4.19"
clap = "3.0.13"
indicatif = "0.16.2"
thiserror = "1.0.30"
