[package]
name = "dlm"
version = "0.1.0"
authors = ["Arnaud Gourlay <arnaud.gourlay@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.3.15"
futures-util = "0.3.15"
hyper = "0.14.9"
reqwest = "0.11.4"
tokio-stream = { version = "0.1.6", features = ["io-util"] }
tokio = { version = "1.8.0", features = ["full"] }
futures-retry = "0.6.0"
chrono = "0.4.19"
clap = "2.33.3"
indicatif = "0.16.2"
